openapi: 3.0.3
info:
  title: Ecommerce API
  description: API documentation for the Ecommerce platform
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/'
paths:
  /login:
    post:
      summary: Check if user exists and login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      role:
                        type: string
                      access_token:
                        type: string
                      refresh_token:
                        type: string
        '400':
          description: Invalid email or password

  /generate-otp:
    get:
      summary: Generate OTP and send email notification
      parameters:
        - in: query
          name: email
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    additionalProperties: true

  /reset-password:
    patch:
      summary: Verify OTP and reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string
                new_password:
                  type: string
              required:
                - email
                - otp
                - new_password
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    additionalProperties: true
        '400':
          description: Invalid OTP or email

  /refresh-auth:
    post:
      summary: Re-generate access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh-token:
                  type: string
              required:
                - refresh-token
      responses:
        '200':
          description: Access token regenerated
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string


  /home:
    get:
      summary: Fetch banner and recent arrived products
      responses:
        '200':
          description: Home page data fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          additionalProperties: true